language: python
matrix:
  include:
    - os: linux
      python:
        - 2.7
        - 3.6
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew upgrade python
        - brew unlink python && brew link python
        - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
        - hash -r
        - pip install --upgrade pip setuptools wheel numpy
env:
- PKG_NAME=limix_lmm
script:
- mkdir -p ~/.config/matplotlib
- 'echo "Backend : Agg" > ~/.config/matplotlib/matplotlibrc'
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - fncpaolo.casale@gmail.com
    on_success: never
    on_failure: always
