language: python
python:
- 2.7
- 3.6
env:
- PKG_NAME=limix_lmm
script:
- mkdir -p ~/.config/matplotlib
- 'echo "Backend : Agg" > ~/.config/matplotlib/matplotlibrc'
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - fncpaolo.casale@gmail.com
    on_success: never
    on_failure: always
